-- Reference rows only (no case data). Generated from backend/app/pipeline/scoring.py CATALOG — keep in sync.
insert into public.indicator_catalog (id, name, modality, "group", method, reference, expected_range) values
 ('face_cnn','Face-manipulation CNN','image','visual','EfficientNet-B4 face-crop classifier; class activation map computed inside the ONNX graph','Tan & Le 2019; Yan et al., DeepfakeBench (NeurIPS 2023)','fake probability < 0.5'),
 ('univfd','Generic AI-generated image detector','image','visual','Frozen CLIP ViT-L/14 embedding + linear probe; 7×7 occlusion map','Ojha, Li & Lee, UnivFD (CVPR 2023)','fake probability < 0.5'),
 ('freq_spectrum','Frequency-domain spectrum','image','visual','Azimuthally averaged log power spectrum: high-frequency ratio, spectral slope, periodic peak strength','Durall et al. 2020; Frank et al., ICML 2020','slope ≈ −2 ± 0.6; peak strength < 6'),
 ('blend_boundary','Blending-boundary discontinuity','image','visual','Laplacian variance and high-pass noise inside the face vs. a ring at the face-mesh boundary','Li & Lyu, Face Warping Artifacts (CVPRW 2019)','|log ratio| sum < 0.8'),
 ('ela','Error Level Analysis','image','visual','Recompress at JPEG quality 90; amplified absolute difference; face vs. background statistics','Krawetz 2007, A Picture''s Worth','|log(face/background)| < 0.5'),
 ('noise_residual','Noise residual consistency','image','visual','Median-filter residual; 32 px block variance; robust z-score outliers','Mahdian & Saic 2009; Lyu, Pan & Zhang 2014','outlier block fraction < 0.05'),
 ('lighting','Lighting consistency (heuristic)','image','visual','Lambertian fit of face-mesh normals to shading; inter-face light angle or cheek shading asymmetry','Johnson & Farid 2005','inconsistency < 0.3'),
 ('landmark_jitter','Landmark temporal jitter','video','temporal','Procrustes-aligned Face Mesh landmarks normalized by inter-ocular distance; second-difference RMS','Sun et al., LRNet (CVPR 2021)','jitter < 0.012 IOD'),
 ('blink','Blink analysis','video','temporal','Eye Aspect Ratio series: blink rate, duration distribution, closure completeness','Soukupová & Čech 2016; Li, Chang & Lyu, In Ictu Oculi (WIFS 2018); Bentivoglio et al. 1997','8–21 blinks/min; 100–400 ms'),
 ('rppg','rPPG biological signal','video','temporal','POS projection of forehead/cheek ROI RGB means, detrend, 0.7–4 Hz band-pass, pulse SNR and cross-ROI coherence','Ciftci, Demir & Yin, FakeCatcher (TPAMI 2020); Wang et al., POS (IEEE TBME 2017)','coherence > 0.5; SNR > 3 dB'),
 ('av_sync','Audio–visual sync','video','temporal','Inner-lip aperture vs. audio RMS envelope: max normalized cross-correlation and lag','Chung & Zisserman, SyncNet (ACCVW 2016)','max corr > 0.3; |lag| < 200 ms'),
 ('container','Container / encoding forensics','video','provenance','ffprobe codec and encoder tags, creation time, re-encode traces, frame-interval irregularity','Milani et al., video forensics overview (APSIPA 2012)','no editor tags; interval CV < 0.1'),
 ('aasist','AASIST-L anti-spoofing','audio','audio','Graph attention over raw-waveform spectro-temporal features; 4 s windows, 50% overlap','Jung et al., AASIST (ICASSP 2022)','spoof probability < 0.5'),
 ('audio_spectral','Spectral artifacts','audio','audio','MFCC/LFCC statistics, spectral flatness, >4 kHz energy, band-limiting cutoff at native sample rate','Frank & Schönherr, WaveFake (NeurIPS 2021); Sahidullah et al. 2015','no sharp cutoff; flatness 0.05–0.3'),
 ('prosody','Prosody','audio','audio','Praat pitch contour: F0 variability, jitter (local), shimmer (local), HNR','Boersma 1993; Teixeira, Oliveira & Lopes 2013','F0 CV 0.1–0.3; jitter 0.4–1.5%; shimmer 2–6%'),
 ('breath_pause','Breath & pause pattern','audio','audio','Energy VAD; inhalation-like low-energy broadband segments between phrases; pause regularity','Mostaani et al., breathing cues for synthetic speech detection (2022)','≥1 breath per 10 s speech; pause CV > 0.3'),
 ('splice','Splice / continuity discontinuity','audio','audio','Robust z-scores of spectral-centroid jumps and phase-advance deviation between frames','Chen et al., audio splicing detection (2017)','max robust z < 6'),
 ('exif_metadata','EXIF/XMP & generator metadata','metadata','provenance','EXIF/XMP tags, PNG text chunks (Stable Diffusion/ComfyUI/Midjourney), timestamp and thumbnail consistency','Kee, Johnson & Farid 2011','camera tags present; no generator tags'),
 ('c2pa','C2PA Content Credentials','metadata','provenance','c2pa-python manifest validation; JUMBF byte-signature fallback','C2PA Technical Specification 2.x','valid manifest without AI assertion'),
 ('duplicate','Duplicate / near-duplicate','metadata','provenance','64-bit DCT perceptual hash; Hamming distance to your previous cases','Zauner 2010, pHash','informational')
on conflict (id) do update set name = excluded.name, modality = excluded.modality, "group" = excluded."group",
  method = excluded.method, reference = excluded.reference, expected_range = excluded.expected_range;
